Refactoring settings + Profile styling / transferring user's data into profile's inputs.
Kh-008-WebUI/Smart-Home pull request #135
Opened 2017-08-02 19:22 UTC by LanaAvry

2017-08-02 19:24 UTC, AnastasiiaHamaiunova approved these changes

2017-08-02 20:15 UTC, tatyana-budnyk approved these changes

2017-08-02 21:07 UTC, tatyana-budnyk requested changes
this will crash existing code

2017-08-03 05:50 UTC, RostyslavSt approved these changes
+

2017-08-03 13:24 UTC, closed without merging